### ISSUE TITLE
Improving background job management

### ISSUE THREAD

**Issue by Slashek** [Platform-OS/platformos-documentation#1282]
As a developer, I would like `admin_background_jobs` to include:
- [ ] - all scheduled jobs using `background` tag
- [ ] - all scheduled jobs using async_callback_actions
- [ ] - all scheduled notifications via form
- [ ] - all failed jobs along with the error message
- [ ] - all jobs in progress

Additionally, as a developer I would like to:
- [ ] - delete job from the queue before it is executed
- [ ] - stop/kill the job which takes too long to execute
- [ ] - re-try failed job
