### ISSUE TITLE
Write onboarding documentation: Get Started — Build Your Own ToDo List App

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#900]
- [x] create example app
- [x] write documentation based on outline (in separate GDoc) 

Part of #479

**Comment by diana-lakatos** [comment]
- [x] add navigation to ToDo App tutorial based on suggestion by @Nagygyorgy

**Comment by diana-lakatos** [comment]
@Nagygyorgy It looks like this, please review: https://diana-documentation.staging.oregon.platform-os.com/get-started/todo-app/build-todo-list-app

**Comment by Nagygyorgy** [comment]
@diana-lakatos The numbering and the items looks great in the sidebar navigation. 

What I'd like to suggest that it would make the experience of these long pages better if we could make the sidebar navigation sticky. So the user can see their actual position and switch between items quickly if needed. This feature could come in one of the next dev rounds.

**Comment by diana-lakatos** [comment]
https://documentation.platformos.com/get-started/todo-app/build-todo-list-app
